server:
  port: 8020

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.190.220:8848
    alibaba:
      seata:
        tx-service-group:
          my_test_tx_group # seata 服务事务分组

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.190.210:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

logging:
  level:
    com.tuling: debug



#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true


seata:
  application-id: ${spring.application.name}
#  设置事务分组
  tx-service-group: my_test_tx_group
# 使用nacos做配置中心后 后需要配置到nacos上
  service:
    vgroup-mapping:
      my_test_tx_group: default
##  只有注册方式使用 file 模式的时候才有效
#    grouplist:
#      default: 192.168.190.220:8091
  registry:
    #指定nacos作为注册中心
    type: nacos
    nacos:
      server-addr: 192.168.190.220:8848
      group: SEATA_GROUP
      cluster: default
      application: seata-server
      namespace:
#  config:
#    # 指定nacos作为配置中心
#    type: nacos
#    nacos:
#      server-addr: 192.168.190.220:8848
#      group: SEATA_GROUP
#      namespace:
#      username:
#      password:
#      data-id: seataCloud.properties.properties



